### ISSUE TITLE
Trim statement spans in error messages

### ISSUE THREAD

**Issue by digama0** [sorear/smetamath-rs#27]
Given the input file `test.mm`:

```
$c x $.
a $p x x $= ? $.
```

Output:

```
$ target/release/smetamath --verify test.mm
test.mm:1:8:Warning:Proof is incomplete
```

Note that there are seven printable characters on the first line, so `1:8` is likely the `\r` before the newline. This is due to the span calculation for the statement, which includes the leading whitespace before the theorem, up through the end of the `$p` statement (which is not being printed in the error message). This span should be shrunk to begin at the `a` label, so that it reads `2:1` instead.

**Comment by sorear** [comment]
It's actually the `\n` itself, but yes.  Realized that last night, was going to fix it but you got there first :+1:
